#!/bin/bash
set -e

# normal files
./node_modules/.bin/coffee -co dist/ source

# lexers
node_modules/.bin/jison-lex -o dist/jade_lexer.js source/jade.jisonlex
echo 'module.exports = jade_lexer;' >> dist/jade_lexer.js

node_modules/.bin/jison-lex -o dist/haml_lexer.js source/haml.jisonlex
echo 'module.exports = haml_lexer;' >> dist/haml_lexer.js

# parser
script/generate_parser.coffee
